services:
  fedora-dev:
    image: theerapats28/fedora-dev:40.01
    container_name: fedora-dev
    ports:
      - "2222:22"
      - "4200:4200"
      - "3000:3000" # ExpressJS
    volumes:
      - ./workspace/1-devs:/home/khunbai/workspace:rw
      - ./ssh:/home/khunbai/.ssh:rw
      - ./pnpm:/home/khunbai/.local/share/pnpm:rw
      - ./config:/home/khunbai/.config:rw
      - ./gitconfig:/home/khunbai/.gitconfig:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Mount the X11 socket, for clipboard sync in nvim.
    environment:
      - DISPLAY=${DISPLAY} # For clipboard sync in nvim.
    restart: always
    networks:
      - dev-network

networks:
  dev-network:
    external: true
