services:
  fedora-dev:
    image: theerapats28/fedora-dev:40.04
    #image: fedora-dev:40.04-test
    container_name: fedora-dev
    ports:
      - "2222:22"
      - "4200:4200"
      - "3000:3000" # ExpressJS
    volumes:
      - ./workspace/1-devs/:/home/khunbai/workspace/:rw
      - ./ssh/:/home/khunbai/.ssh/:rw
      - ./pnpm/:/home/khunbai/.local/share/pnpm/:rw
      - ./config/nvim/:/home/khunbai/.config/nvim/:rw
      - ./config/github-copilot/:/home/khunbai/.config/github-copilot/:rw
      - ./config/ranger/:/home/khunbai/.config/ranger/:rw
      - ./config/tmux/:/home/khunbai/.config/tmux/:rw
      - ./config/git/gitconfig:/home/khunbai/.gitconfig:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Mount the X11 socket, for clipboard sync in nvim.
      # For Wayland system use wl-clipboard
      - /usr/bin/wl-copy:/usr/bin/wl-copy:rw
      - /usr/bin/wl-paste:/usr/bin/wl-paste:rw
      - ${XDG_RUNTIME_DIR}/wayland-0:${XDG_RUNTIME_DIR}/wayland-0:rw
    environment:
      - TZ=Asia/Bangkok
      - DISPLAY=${DISPLAY} # For clipboard sync in nvim.
      # Wayland clipboard sync
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    restart: always
    networks:
      - dev-network

networks:
  dev-network:
    external: true
