services:
  fedora-dev:
    image: fedora-dev:40
    container_name: fedora-dev
    ports:
      - "2222:22"
      - "4200:4200"
    volumes:
      - ./ssh:/root/.ssh
      - ./pnpm:/root/.local/share/pnpm
      - ./workspace:/workspace
      - ./config:/root/.config
    restart: always